hash-format = "sha256"

[[files]]
file = "mods/accessories-tc-layer.pw.toml"
metafile = true

[[files]]
file = "mods/accessories.pw.toml"
metafile = true

[[files]]
file = "mods/additional-lanterns.pw.toml"
metafile = true

[[files]]
file = "mods/additional-structures.pw.toml"
metafile = true

[[files]]
file = "mods/alloy-forgery.pw.toml"
metafile = true

[[files]]
file = "mods/almost-unified.pw.toml"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
metafile = true

[[files]]
file = "mods/amplified-nether-height.pw.toml"
metafile = true

[[files]]
file = "mods/amplified-nether.pw.toml"
metafile = true

[[files]]
file = "mods/analog.pw.toml"
metafile = true

[[files]]
file = "mods/animal_feeding_trough.pw.toml"
metafile = true

[[files]]
file = "mods/anyscale.pw.toml"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
metafile = true

[[files]]
file = "mods/artifacts.pw.toml"
metafile = true

[[files]]
file = "mods/artsandcrafts.pw.toml"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
metafile = true

[[files]]
file = "mods/atlas-core.pw.toml"
metafile = true

[[files]]
file = "mods/auto-workstations.pw.toml"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
metafile = true

[[files]]
file = "mods/beautify-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/better-third-person.pw.toml"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
metafile = true

[[files]]
file = "mods/betternether.pw.toml"
metafile = true

[[files]]
file = "mods/beyondenchant.pw.toml"
metafile = true

[[files]]
file = "mods/big-pony.pw.toml"
metafile = true

[[files]]
file = "mods/biolith.pw.toml"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/blahaj_fabric.pw.toml"
metafile = true

[[files]]
file = "mods/blockus.pw.toml"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
metafile = true

[[files]]
file = "mods/blur-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/bobby.pw.toml"
metafile = true

[[files]]
file = "mods/bountiful-blocks.pw.toml"
metafile = true

[[files]]
file = "mods/brrp.pw.toml"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/camerapture.pw.toml"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
metafile = true

[[files]]
file = "mods/chat-heads.pw.toml"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
metafile = true

[[files]]
file = "mods/chisel-reborn.pw.toml"
metafile = true

[[files]]
file = "mods/chococraft.pw.toml"
metafile = true

[[files]]
file = "mods/cicada.pw.toml"
metafile = true

[[files]]
file = "mods/cinderscapes.pw.toml"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
metafile = true

[[files]]
file = "mods/connectiblechains.pw.toml"
metafile = true

[[files]]
file = "mods/construction-wand-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
metafile = true

[[files]]
file = "mods/craftpresence.pw.toml"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
metafile = true

[[files]]
file = "mods/crate-delight.pw.toml"
metafile = true

[[files]]
file = "mods/creeper-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/debugify.pw.toml"
metafile = true

[[files]]
file = "mods/decorative-lamps.pw.toml"
metafile = true

[[files]]
file = "mods/deeperdarker.pw.toml"
metafile = true

[[files]]
file = "mods/dense-flowers.pw.toml"
metafile = true

[[files]]
file = "mods/do-a-barrel-roll.pw.toml"
metafile = true

[[files]]
file = "mods/double-doors.pw.toml"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
metafile = true

[[files]]
file = "mods/elytra-trims.pw.toml"
metafile = true

[[files]]
file = "mods/emi-loot.pw.toml"
metafile = true

[[files]]
file = "mods/emi.pw.toml"
metafile = true

[[files]]
file = "mods/endrem.pw.toml"
metafile = true

[[files]]
file = "mods/enhanced-groups.pw.toml"
metafile = true

[[files]]
file = "mods/entity-model-features.pw.toml"
metafile = true

[[files]]
file = "mods/entitytexturefeatures.pw.toml"
metafile = true

[[files]]
file = "mods/esf.pw.toml"
metafile = true

[[files]]
file = "mods/eternal-starlight.pw.toml"
metafile = true

[[files]]
file = "mods/excessive-building.pw.toml"
metafile = true

[[files]]
file = "mods/exlines-furniture.pw.toml"
metafile = true

[[files]]
file = "mods/expanded-storage.pw.toml"
metafile = true

[[files]]
file = "mods/explosive-enhancement.pw.toml"
metafile = true

[[files]]
file = "mods/extended-drawers.pw.toml"
metafile = true

[[files]]
file = "mods/extshape.pw.toml"
metafile = true

[[files]]
file = "mods/extshape_blockus.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
metafile = true

[[files]]
file = "mods/fabricbettergrass.pw.toml"
metafile = true

[[files]]
file = "mods/fabricskyboxes-interop.pw.toml"
metafile = true

[[files]]
file = "mods/fabricskyboxes.pw.toml"
metafile = true

[[files]]
file = "mods/factory-blocks.pw.toml"
metafile = true

[[files]]
file = "mods/faewufs-diversity.pw.toml"
metafile = true

[[files]]
file = "mods/fallingleaves.pw.toml"
metafile = true

[[files]]
file = "mods/fallingtree.pw.toml"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
metafile = true

[[files]]
file = "mods/faux-custom-entity-data.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/fish-of-thieves.pw.toml"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes-beekeeper-hut-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes-flowery-mooblooms-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/friends-and-foes.pw.toml"
metafile = true

[[files]]
file = "mods/fusion-connected-textures.pw.toml"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
metafile = true

[[files]]
file = "mods/geckoanimfix.pw.toml"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
metafile = true

[[files]]
file = "mods/grass-overhaul.pw.toml"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
metafile = true

[[files]]
file = "mods/hd-skins.pw.toml"
metafile = true

[[files]]
file = "mods/ichunutil.pw.toml"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
metafile = true

[[files]]
file = "mods/immersivethunder.pw.toml"
metafile = true

[[files]]
file = "mods/improved-anvils.pw.toml"
metafile = true

[[files]]
file = "mods/inventive-inventory.pw.toml"
metafile = true

[[files]]
file = "mods/inventory-profiles-next.pw.toml"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
metafile = true

[[files]]
file = "mods/katters-structures.pw.toml"
metafile = true

[[files]]
file = "mods/kirin.pw.toml"
metafile = true

[[files]]
file = "mods/kiwi.pw.toml"
metafile = true

[[files]]
file = "mods/ksyxis.pw.toml"
metafile = true

[[files]]
file = "mods/lavender.pw.toml"
metafile = true

[[files]]
file = "mods/ledger.pw.toml"
metafile = true

[[files]]
file = "mods/let-sleeping-dogs-lie.pw.toml"
metafile = true

[[files]]
file = "mods/libipn.pw.toml"
metafile = true

[[files]]
file = "mods/lighty.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-bridges-biome-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-fences-biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-holidays.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-paths-and-pavings.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-roofs-biomes-o-plenty.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
metafile = true

[[files]]
file = "mods/mambience.pw.toml"
metafile = true

[[files]]
file = "mods/mavapi.pw.toml"
metafile = true

[[files]]
file = "mods/mavm.pw.toml"
metafile = true

[[files]]
file = "mods/midnightlib.pw.toml"
metafile = true

[[files]]
file = "mods/mine-little-pony.pw.toml"
metafile = true

[[files]]
file = "mods/mo-structures.pw.toml"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/monolib.pw.toml"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
metafile = true

[[files]]
file = "mods/more-barrel-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-bed-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-beehive-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-bookshelf-variants-lieonlion.pw.toml"
metafile = true

[[files]]
file = "mods/more-cartography-tables.pw.toml"
metafile = true

[[files]]
file = "mods/more-chest-variants-lieonlion.pw.toml"
metafile = true

[[files]]
file = "mods/more-chiseled-bookshelf-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-composter-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-crafter-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-crafting-tables-lieonlion.pw.toml"
metafile = true

[[files]]
file = "mods/more-feeding-trough-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-furnace-variants-lieonlion.pw.toml"
metafile = true

[[files]]
file = "mods/more-grindstone-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-jukebox-noteblock-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-lectern-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-loom-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-mob-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-shield-variants.pw.toml"
metafile = true

[[files]]
file = "mods/more-smithing-tables.pw.toml"
metafile = true

[[files]]
file = "mods/more-smoker-variants.pw.toml"
metafile = true

[[files]]
file = "mods/mythic-upgrades.pw.toml"
metafile = true

[[files]]
file = "mods/natural-size-variation.pw.toml"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
metafile = true

[[files]]
file = "mods/necronomicon.pw.toml"
metafile = true

[[files]]
file = "mods/nemos-mossy-blocks.pw.toml"
metafile = true

[[files]]
file = "mods/neoenchant.pw.toml"
metafile = true

[[files]]
file = "mods/neruina.pw.toml"
metafile = true

[[files]]
file = "mods/new-slab-variants.pw.toml"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
metafile = true

[[files]]
file = "mods/noisium.pw.toml"
metafile = true

[[files]]
file = "mods/optigui.pw.toml"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
metafile = true

[[files]]
file = "mods/particular.pw.toml"
metafile = true

[[files]]
file = "mods/pehkui.pw.toml"
metafile = true

[[files]]
file = "mods/philips-ruins.pw.toml"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
metafile = true

[[files]]
file = "mods/presence-footsteps.pw.toml"
metafile = true

[[files]]
file = "mods/psychedelicraft.pw.toml"
metafile = true

[[files]]
file = "mods/pumpkin-pie-delight.pw.toml"
metafile = true

[[files]]
file = "mods/qraftyfied.pw.toml"
metafile = true

[[files]]
file = "mods/quad.pw.toml"
metafile = true

[[files]]
file = "mods/railroad-blocks.pw.toml"
metafile = true

[[files]]
file = "mods/raknetify.pw.toml"
metafile = true

[[files]]
file = "mods/reborncore.pw.toml"
metafile = true

[[files]]
file = "mods/rechiseled.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/refinedstorage-emi-integration.pw.toml"
metafile = true

[[files]]
file = "mods/refinedstorage-trinkets-integration.pw.toml"
metafile = true

[[files]]
file = "mods/refinedstorage.pw.toml"
metafile = true

[[files]]
file = "mods/replanting-crops.pw.toml"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
metafile = true

[[files]]
file = "mods/rolling-down-in-the-deep.pw.toml"
metafile = true

[[files]]
file = "mods/seasonhud-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/serene-seasons.pw.toml"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
metafile = true

[[files]]
file = "mods/shulkerboxtooltip.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/skylands-over-the-sea.pw.toml"
metafile = true

[[files]]
file = "mods/smarter-farmers-farmers-replant.pw.toml"
metafile = true

[[files]]
file = "mods/snow-real-magic.pw.toml"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/sooty-chimneys.pw.toml"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/stackdeobf.pw.toml"
metafile = true

[[files]]
file = "mods/status-effect-bars.pw.toml"
metafile = true

[[files]]
file = "mods/storage-delight.pw.toml"
metafile = true

[[files]]
file = "mods/stringer-things.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
metafile = true

[[files]]
file = "mods/techreborn.pw.toml"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
metafile = true

[[files]]
file = "mods/the-bumblezone-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/tla-api.pw.toml"
metafile = true

[[files]]
file = "mods/toms-storage.pw.toml"
metafile = true

[[files]]
file = "mods/trade-cycling.pw.toml"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
metafile = true

[[files]]
file = "mods/traverse.pw.toml"
metafile = true

[[files]]
file = "mods/trowel.pw.toml"
metafile = true

[[files]]
file = "mods/unilib.pw.toml"
metafile = true

[[files]]
file = "mods/vanilla-fireflies.pw.toml"
metafile = true

[[files]]
file = "mods/variants-and-ventures.pw.toml"
metafile = true

[[files]]
file = "mods/vistas.pw.toml"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
metafile = true

[[files]]
file = "mods/voice-chat-interaction.pw.toml"
metafile = true

[[files]]
file = "mods/void-fog.pw.toml"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
metafile = true

[[files]]
file = "mods/where-is-it.pw.toml"
metafile = true

[[files]]
file = "mods/wilder-wild.pw.toml"
metafile = true

[[files]]
file = "mods/wits.pw.toml"
metafile = true

[[files]]
file = "mods/worldweaver.pw.toml"
metafile = true

[[files]]
file = "mods/wunderreich.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
metafile = true
