name = "Sky Craft 2"
author = "Sky Splash"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc915ea3a822abe7b3ce1a50c6c4f85c8c86568fe79f46ca1388b129cba1b01b"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
