name = "Sky Craft 2"
author = "Sky Splash"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "da618ada6ac1c0a79ed944b28394a72d1e7b690d4bf50b7544c1a96ef9d2fcab"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
