name = "Sky Craft 2"
author = "Sky Splash"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3ed8c2719bfd1928609300ef79f43dce141752c94263cf07082126f76f90feed"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
