name = "Sky Craft 2"
author = "Sky Splash"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ff9d342b8f4a45155a4ef3f308a3bf20e2c11968a12fb84da1d9bfa8522996a"

[versions]
fabric = "0.16.0"
minecraft = "1.21"
