name = "Sky Craft 2"
author = "Sky Splash"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d220e476f36b92b0960fd4a5d05f056759a001f97bd9762662cd365b628db6df"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
