name = "Sky Craft 2"
author = "Sky Splash"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "093403f52b33251fb5796f9865f009161737101e4b69fa78def6b2d7cd4dd2f9"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
