name = "Sky Craft 2"
author = "Sky Splash"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c4ef40be54f97b717dfc75734c2a2f7c331ac434b9becc86b7242cd607dc319"

[versions]
fabric = "0.15.11"
minecraft = "1.21"
